# Sophos_Central filter using "SF syslog file guide 20.0", version 1.0.0

# See: https://docs.sophos.com/nsg/sophos-firewall/20.0/pdf/sf-syslog-guide-20.0.pdf
# and https://docs.sophos.com/nsg/sophos-firewall/20.0/Help/en-us/webhelp/onlinehelp/AdministratorHelp/Logs/TroubleshootingLogs/LogFileDetails/index.html#https-ftp-waf

pipeline:
  - dataTypes:
      - sophos-central
    steps:
      - json:
          source: raw

      - rename:
          from:
            - log.coreremedyitems
          to: log.coreremedyItems

      - rename:
          from:
            - log.createdat
          to: log.createdAt

      - rename:
          from:
            - log.customerid
          to: log.customerId

      - rename:
          from:
            - log.endpointid
          to: log.endpointId

      - rename:
          from:
            - log.endpointtype
          to: log.endpointType

      - rename:
          from:
            - log.sourceinfo.ip
          to: log.ip

      - rename:
          from:
            - log.userid
          to: log.userId

      - rename:
          from:
            - log.sourceinfo
          to: log.sourceInfo