# Postgres module filter, version 3.0.0
# Filter Input requirements -> fileset: datatype
#                              log    : plain text
# 
# Documentations
# 1- https://www.postgresql.org/docs/
# 2- https://www.postgresql.org/docs/current/runtime-config-logging.html
# 3- https://www.elastic.co/guide/en/beats/filebeat/7.13/filebeat-module-postgresql.html
# 
# Implementation
# 1. Parsing the json from beats
# 2. Parsing the message field containing the postgres log
pipeline:
  - dataTypes:
      - postgresql
    steps:
      - json:
          source: raw

      # Parse beats field    
      - rename:
          from:
            - log.url
          to: origin.url

      - rename:
          from:
            - log.log.file.path
          to: origin.file

      - rename:
          from:
            - log.host.ip
          to: log.origin.ips

      - rename:
          from:
            - log.host.mac
          to: log.origin.macs

      - rename:
          from:
            - log.host.hostname
          to: origin.host

      - rename:
          from:
            - log.event.dataset
          to: action

      - rename:
          from:
            - log.agent.version
          to: log.agentVersion

      - rename:
          from:
            - log.host.os.kernel
          to: log.osVersion

      - rename:
          from:
            - log.host.os.type
          to: log.osType

      - rename:
          from:
            - log.host.architecture
          to: log.cpuArchitecture

      # Fields conversions
      - cast:
          to: '[]string'
          fields:
            - log.origin.ips
      - cast:
          to: '[]string'
          fields:
            - log.origin.macs

      # Common postgresql log parsing
      # Example Log 
      # Mar 24 14:58:08 webappsecure postgres[7694]: [10-2] 42701 530b5e00.1e0e STATEMENT: ALTER TABLE sessiongroup ADD COLUMN requests bigint    
      - grok:
          patterns:
            - fieldName: log.deviceTime
              pattern: '{{.monthName}}{{.space}}{{.monthDay}}{{.space}}{{.time}} | 
                        {{.year}}(-){{.monthNumber}}(-){{.monthDay}}{{.space}}{{.time}}{{.space}}((UTC)?)'
            - fieldName: target.host
              pattern: '{{.hostname}}'
            - fieldName: log.irrelevant
              pattern: '{{.word}}'
            - fieldName: log.processId
              pattern: '\[{{.data}}\](\:)?'
            - fieldName: log.groupId
              pattern: '\[{{.data}}\]'
            - fieldName: log.errorCode
              pattern: '{{.integer}}'
            - fieldName: log.sessionId
              pattern: '([0-9a-f]{8}\.[0-9a-f]{4})'
            - fieldName: log.messageType
              pattern: '{{.word}}(\:)?'
            - fieldName: log.msg
              pattern: '{{.greedy}}' 
          source: log.message

      # Common postgresql log parsing
      # Example Log 
      # 2022-02-15 19:43:52.364 UTC [25] LOG:  database system was shut down at 2022-02-11 20:01:30 UTC
      - grok:
          patterns:
            - fieldName: log.deviceTime
              pattern: '{{.year}}(-){{.monthNumber}}(-){{.monthDay}}{{.space}}{{.time}}{{.space}}((UTC)?) |
                        {{.monthName}}{{.space}}{{.monthDay}}{{.space}}{{.time}}'
            - fieldName: log.groupId
              pattern: '\[{{.data}}\]'
            - fieldName: log.messageType
              pattern: '{{.word}}(\:)?'
            - fieldName: log.msg
              pattern: '{{.greedy}}' 
          source: log.message

      # Removing unused caracters
      - trim:
          function: prefix
          substring: '['
          fields:
            - log.processId
            - log.groupId
      - trim:
          function: suffix
          substring: ':'
          fields:
            - log.processId
            - log.messageType
      - trim:
          function: suffix
          substring: ']'
          fields:
            - log.processId
            - log.groupId
  
      # Removing unused fields
      - delete:
          fields:
            - log.service
            - log.metadata
            - log.agent
            - log.host
            - log.event
            - log.ecs
            - log.log
            - log.irrelevant