- id: 1012
  dataTypes:
    - cs_switch
  name: Configuration Rollback Event Detected
  impact:
    confidentiality: 2
    integrity: 5
    availability: 3
  category: Configuration Management
  technique: Account Manipulation
  adversary: destination
  references:
    - https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9400/software/release/17-13/configuration_guide/sys_mgmt/b_1713_sys_mgmt_9400_cg/configuring_system_message_logs.html
    - https://attack.mitre.org/techniques/T1098/
  description: Detects configuration rollback events on Cisco switches which may indicate unauthorized changes being reverted or system recovery actions
  where: |
    (safe(log.facility, "") == "SYS" || safe(log.facility, "") == "CONFIG") &&
    (safe(log.mnemonic, "") == "CONFIG_I" || 
     safe(log.mnemonic, "") == "ROLLBACK" ||
     contains(safe(log.message, ""), "configuration rollback") ||
     contains(safe(log.message, ""), "config reverted") ||
     contains(safe(log.message, ""), "startup-config replaced") ||
     contains(safe(log.message, ""), "configuration restored"))
  afterEvents:
    - indexPattern: v11-log-*
      with:
        - field: destination.device.keyword
          operator: filter_term
          value: '{{destination.device}}'
      within: now-1h
      count: 2
  deduplicateBy:
    - destination.device