- id: 1019
  dataTypes:
    - vmware-esxi
  name: Suspicious OVF/OVA Deployment
  impact:
    confidentiality: 4
    integrity: 4
    availability: 3
  category: Deployment Security
  technique: Malicious Image Deployment
  adversary: origin
  references:
    - https://www.nakivo.com/blog/vmware-logs-analysis-for-troubleshooting/
    - https://attack.mitre.org/techniques/T1608/004/
  description: Detects potentially malicious OVF/OVA deployments that could introduce compromised virtual machines into the environment. Monitors for rapid deployments, deployments from unusual sources, or deployments with suspicious configurations.
  where: |
    (safe(log.message, "") contains "ImportVApp" ||
     safe(log.message, "") contains "DeployOvf" ||
     safe(log.message, "") contains "ovftool" ||
     safe(log.message, "") contains ".ovf" ||
     safe(log.message, "") contains ".ova") &&
    (safe(log.message, "") contains "http://" ||
     safe(log.message, "") contains "https://" ||
     safe(log.message, "") contains "ftp://" ||
     safe(log.process, "") == "hostd" ||
     safe(severity, "") == "warning" ||
     safe(severity, "") == "error")
  afterEvents:
    - indexPattern: v11-log-*
      with:
        - field: origin.hostname.keyword
          operator: filter_term
          value: '{{origin.hostname}}'
      within: now-1h
      count: 3
  deduplicateBy:
    - origin.hostname
    - log.pid