- id: 1013
  dataTypes:
    - haproxy
  name: HAProxy Configuration Injection Attempts
  impact:
    confidentiality: 2
    integrity: 5
    availability: 3
  category: Initial Access
  technique: T1190 - Exploit Public-Facing Application
  adversary: origin
  references:
    - https://www.haproxy.com/blog/haproxy-log-customization
    - https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=HAProxy
    - https://attack.mitre.org/techniques/T1190/
  description: Detects attempts to inject malicious configuration directives through HAProxy interfaces or logs. This could indicate an attempt to modify routing rules, ACLs, or backend server configurations through injection vulnerabilities.
  where: |
    safe(action, "") == "haproxy.log" && 
    (safe(log.message, "") matches ".*\\b(backend|frontend|listen|bind|server|acl|use_backend|redirect|option|timeout)\\s+[^\\s]*[;<>&|`$(){}\\[\\]].*" || 
     safe(origin.url, "") matches ".*[;<>&|`$(){}\\[\\]].*config.*" || 
     safe(log.http.request.body.content, "") matches ".*\\b(backend|frontend|listen|bind|server)\\s+.*")
  afterEvents:
    - indexPattern: v11-log-*
      with:
        - field: origin.ip.keyword
          operator: filter_term
          value: '{{origin.ip}}'
      within: now-10m
      count: 3
  deduplicateBy:
    - origin.ip
    - log.message