- id: 1024
  dataTypes:
    - firewall-pfsense
  name: pfSense Configuration Backup Failure
  impact:
    confidentiality: 1
    integrity: 4
    availability: 3
  category: System Configuration
  technique: Data Destruction
  adversary: system
  references:
    - https://docs.netgate.com/pfsense/en/latest/backup/index.html
    - https://attack.mitre.org/techniques/T1485/
  description: Detects configuration backup failures in pfSense. Failed backups can prevent disaster recovery and may indicate storage issues, permission problems, or potential tampering with backup processes. Regular successful backups are critical for system recovery.
  where: (safe(log.eventType, "") == "system" || safe(log.eventType, "") == "config") && (safe(raw, "").contains("backup failed") || safe(raw, "").contains("config write error") || safe(raw, "").contains("unable to save") || safe(raw, "").contains("backup error") || safe(raw, "").contains("configuration sync failed") || safe(raw, "").contains("xmlrpc sync error"))
  deduplicateBy:
    - log.syslogHost