# ESET filter version 3.0.2
# Based in docs
# 
# Documentations
# 1- https://help.eset.com/esmc_admin/70/en-US/events-exported-to-json-format.html#custom_keys
# 
# Implementation
# 1. Parsing headers of syslog the message
# 2. Parsing RAW field log
pipeline:
  - dataTypes:
      - antivirus-esmc-eset
    steps:
      # Parsing RAW field log
      - grok:
          patterns:
            - fieldName: log.priority
              pattern: '\<{{.data}}\>'
            - fieldName: log.msgType
              pattern: '{{.integer}}'
            - fieldName: log.deviceTime
              pattern: '{{.year}}(-){{.monthNumber}}(-){{.monthDay}}(T){{.time}}(Z)'
            - fieldName: log.headHostname
              pattern: '{{.hostname}}'
            - fieldName: log.serviceName
              pattern: '{{.hostname}}'
            - fieldName: log.pid
              pattern: '{{.integer}}'
            - fieldName: log.restHead
              pattern: '\-{{.data}}\-'
            - fieldName: log.jsonMessage
              pattern: '{{.greedy}}'

      # Remove inecesarie caracters
      - trim:
          function: prefix
          substring: '<'
          fields:
            - log.priority
      - trim:
          function: suffix
          substring: '>'
          fields:
            - log.priority

      # Parsing jsonMessage field log
      - json:
          source: log.jsonMessage
      
      - rename:
          from:
            - log.ipv4
          to: target.ip
      - rename:
          from:
            - log.hostname
          to: target.host
      - rename:
          from:
            - log.action
          to: action
      - rename:
          from:
            - log.event
          to: actionResult
      - rename:
          from:
            - log.sourceaddress
          to: origin.ip
      - rename:
          from:
            - log.protocol
          to: protocol
      - rename:
          from:
            - log.sourceport
          to: origin.port
      - rename:
          from:
            - log.targetaddress
          to: target.ip
      - rename:
          from:
            - log.targetport
          to: target.port
      
      # Adding severity field based on log.severity
      - add:
          function: 'string'
          params:
            key: severity
            value: 'low'
          where: safe("log.severity", "") && ( log.severity=="INFO" || log.severity=="Info" )

      - add:
          function: 'string'
          params:
            key: severity
            value: 'medium'
          where: safe("log.severity", "") && (log.severity=="WARNING" || log.severity=="Warning")

      - add:
          function: 'string'
          params:
            key: severity
            value: 'high'
          where: safe("log.severity", "") && (log.severity=="ERROR" || log.severity=="Error")

      # Adding geolocation to origin.ip
      - dynamic:
          plugin: com.utmstack.geolocation
          params:
            source: origin.ip
            destination: origin.geolocation
          where: exists("origin.ip")
      
      # Adding geolocation to target.ip
      - dynamic:
          plugin: com.utmstack.geolocation
          params:
            source: target.ip
            destination: target.geolocation
          where: exists("target.ip")

      # Removing unused fields
      - delete:
          fields:
            - log.jsonMessage
            - log.severity