# VMWare-ESXi, version 3.0.0
# 
# Based on docs and real logs provided
# Support VMWare-ESXi log
#
# Documentations
# 1- https://core.vmware.com/esxi-log-message-formats
#
# Implementation
# 1. Parsing headers of syslog the message 
# 2. Parsing the RAW field containing the VMWare-ESXi
pipeline:
  - dataTypes:
      - vmware-esxi
    steps:
      - grok:
          patterns:
            - fieldName: log.priority
              pattern: '\<{{.data}}\>'
            - fieldName: log.deviceTime
              pattern: '{{.year}}(-){{.monthNumber}}(-){{.monthDay}}(T){{.time}}(Z)'
            - fieldName: origin.hostname
              pattern: '{{.hostname}}'
            - fieldName: log.process
              pattern: '{{.hostname}}(\:)'
            - fieldName: severity
              pattern: '{{.word}}'
            - fieldName: log.processName
              pattern: '{{.hostname}}'
            - fieldName: log.pid
              pattern: '\[{{.data}}\]'
            - fieldName: log.eventInfo
              pattern: '\[{{.data}}\]'
            - fieldName: log.message
              pattern: '{{.greedy}}'

      - grok:
          patterns:
            - fieldName: log.priority
              pattern: '\<{{.data}}\>'
            - fieldName: log.deviceTime
              pattern: '{{.year}}(-){{.monthNumber}}(-){{.monthDay}}(T){{.time}}(Z)'
            - fieldName: origin.hostname
              pattern: '{{.hostname}}'
            - fieldName: log.process
              pattern: '{{.hostname}}'
            - fieldName: log.pid
              pattern: '\[{{.data}}\]:'
            - fieldName: log.message
              pattern: '{{.greedy}}'
              
      # Removing unused caracters
      - trim:
          function: prefix
          substring: '<'
          fields:
            - log.priority
      - trim:
          function: prefix
          substring: '['
          fields:
            - log.pid
            - log.eventInfo
      - trim:
          function: suffix
          substring: '>'
          fields:
            - log.priority
      - trim:
          function: suffix
          substring: ':'
          fields:
            - log.pid
            - log.process
      - trim:
          function: suffix
          substring: ']'
          fields:
            - log.pid
            - log.eventInfo
                    
      # Removing unused fields
      - delete:
          fields:
            - log.processName