- id: 1016
  dataTypes:
    - traefik_module
  name: Traefik File Provider Exploits
  impact:
    confidentiality: 4
    integrity: 5
    availability: 3
  category: Configuration Manipulation
  technique: External Remote Services
  adversary: origin
  references:
    - https://doc.traefik.io/traefik/providers/file/
    - https://attack.mitre.org/techniques/T1133/
  description: Detects attempts to exploit Traefik's file provider through unauthorized configuration changes, malicious file uploads, or directory traversal attempts targeting configuration files. Monitors for suspicious access patterns to configuration directories and attempts to modify dynamic configuration files.
  where: |
    safe(action, "") == "traefik.access" && 
    (
      (safe(log.RequestPath, "") contains ".." && safe(log.RequestPath, "") contains "conf") ||
      (safe(log.RequestPath, "") contains "/etc/traefik" && safe(log.RequestMethod, "") in ["PUT", "POST", "PATCH"]) ||
      (safe(log.RequestPath, "") matches ".*\\.(yml|yaml|toml)$" && safe(log.StatusCode, 0) >= 400) ||
      (safe(log.error, "") contains "file provider" && safe(log.error, "") contains "permission denied") ||
      (safe(log.msg, "") contains "dynamic configuration" && safe(log.msg, "") contains "reload") ||
      (safe(log.provider, "") == "file" && safe(log.event, "") == "error")
    )
  afterEvents:
    - indexPattern: v11-log-*
      with:
        - field: origin.ip.keyword
          operator: filter_term
          value: '{{origin.ip}}'
      within: now-15m
      count: 10
  deduplicateBy:
    - origin.ip
    - log.RequestPath