- id: 1013
  dataTypes:
    - traefik
  name: Tracing Data Exposure Detection
  impact:
    confidentiality: 5
    integrity: 2
    availability: 1
  category: Information Disclosure
  technique: System Network Configuration Discovery
  adversary: origin
  references:
    - https://doc.traefik.io/traefik/observability/tracing/
    - https://attack.mitre.org/techniques/T1016/
  description: Detects access to tracing endpoints or headers that could expose sensitive request flow information, service dependencies, and performance metrics
  where: |
    (safe(log.http.request_headers.x_trace_id, "") != "" ||
     safe(log.http.request_headers.x_span_id, "") != "" ||
     safe(log.http.request_headers.x_b3_traceid, "") != "" ||
     safe(log.http.request_headers.traceparent, "") != "" ||
     safe(origin.url, "") contains "/debug/pprof" ||
     safe(origin.url, "") contains "/trace") &&
    safe(log.http.response_code, 0) < 400
  afterEvents:
    - indexPattern: v11-log-*
      with:
        - field: origin.ip.keyword
          operator: filter_term
          value: '{{origin.ip}}'
      within: now-10m
      count: 3
  deduplicateBy:
    - origin.ip
    - log.http.request_headers.x_trace_id