- id: 1001
  dataTypes:
    - nginx
  name: Nginx Configuration Injection Attempt
  impact:
    confidentiality: 4
    integrity: 5
    availability: 3
  category: Web Application Attack
  technique: Configuration Injection
  adversary: origin
  references:
    - https://blog.detectify.com/industry-insights/common-nginx-misconfigurations-that-leave-your-web-server-ope-to-attack/
    - https://attack.mitre.org/techniques/T1055/
  description: Detects attempts to inject malicious content into nginx configuration through CRLF injection, path traversal, or variable manipulation. Monitors for URL-encoded CRLF characters, attempts to access configuration files, and suspicious variable usage patterns.
  where: |
    safe(origin.ip, "") != "" && 
    safe(origin.path, "") != "" &&
    (
      origin.path.contains("%0d%0a") ||
      origin.path.contains("%0D%0A") ||
      origin.path.contains("/nginx.conf") ||
      origin.path.contains("/etc/nginx") ||
      origin.path.contains("../") ||
      origin.path.contains("..\\") ||
      (safe(log.request, "") != "" && (log.request.contains("$uri") || log.request.contains("$document_uri"))) ||
      (safe(log.userAgent, "") != "" && log.userAgent.contains("<?php"))
    )
  afterEvents:
    - indexPattern: v11-log-*
      with:
        - field: origin.ip.keyword
          operator: filter_term
          value: '{{origin.ip}}'
      within: now-15m
      count: 3
  deduplicateBy:
    - origin.ip
    - origin.path